posgres-data:
  image: busybox
  volumes:
    - /var/lib/postgresql/log-collector-data
  container_name: log-collector-postgres-datastore

postgresql:
  image: postgres
  enviroment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
  ports:
    - "5432:5432"
  volumes_from:
    - posgres-data